spring:
  application:
    name: backend-part

  datasource:
    url: jdbc:postgresql://localhost:5432/AI-Vulnerability-Prioritizer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
    secretKey: ${JWT_SECRET}
app:
  base-url: ${BASE_URL}
github:
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  redirect-uri: http://127.0.0.1:8080/integrations/github/callback